completeWhileTyping: true
completion-menu.completion: 'bg:#000000 #ffffff'
completion-menu.completion.current: 'bg:#00aaaa #000000'
default: 'gold'
downloadDict:
- downloadDict.yml
fuzzycomplete: true
mode: CMD
mouseSupport: true
multithreading: true
path: 'greenyellow'
pointer: '#b20000'
scrollbar.background: bg:#88aaaa
scrollbar.button: bg:#222222
searchIgnoreCase: true
user: '#ff4500'
welcome: false
wrapLines: true
