completeWhileTyping: true
completion-menu.completion: 'bg:#000000 #ffffff'
completion-menu.completion.current: 'bg:#00aaaa #000000'
default: greenyellow
downloadDict: downloadDict.yml
exeptions: [instaloader]
fuzzycomplete: true
mode: CMD
mouseSupport: true
multithreading: true
path: aqua
pointer: '#ff4500'
scrollbar.background: bg:#88aaaa
scrollbar.button: bg:#222222
searchIgnoreCase: true
user: '#ff4500'
welcome: false
wrapLines: true
